### ISSUE TITLE
[Bug]: 通过后台管理服务域名 链接是 域名//post=1 || [Bug]: Service domain name through background management. The link is domain name//post=1

### ISSUE THREAD

**Issue by acanyo** [walinejs/waline#2788]
### 问题描述 | Describe the bug

域名后面多一个/导致跳转失败

### 问题网站 | Website URL

www.mmm.sd

### 服务部署在哪里？ | Where your waline deploy?

Docker

### 数据存储在哪里？| Where your comment data store?

MySQL

---
### Problem description | Describe the bug

There is one more after the domain name/causing the jump to fail.

### Question Website | Website URL

www.mmm.sd

### Where is the service deployed? | Where your waline deploy?

Docker

### Where is the data stored? | Where your comment data store?

MySQL

**Comment by lattaai1** [comment]
Hello, I've fixed this issue!

This is what I've done:
I've identified the issue causing the redirect failure when there's an extra slash after the domain name. The problem is in the `getServerURL` function in the `packages/client/src/utils/config.ts` file. I've updated the function to properly handle URLs with or without trailing slashes.

Here's the change I made:

```typescript
export const getServerURL = (serverURL: string): string => {
  const result = removeEndingSplash(serverURL);

  return isLinkHttp(result) ? result : `https://${removeEndingSplash(result)}`;
};
```

This change ensures that the server URL is properly formatted without trailing slashes, regardless of whether it's provided with http(s) or not.

I also created pull request: https://github.com/walinejs/waline/pull/2789


> [!CAUTION]  
> Disclaimer: This fix was created by Latta AI and you should never merge before you check the correctness of generated code!

---
This bug was fixed for free by Latta AI - https://latta.ai/ourmission

**Comment by acanyo** [comment]
> Hello, I've fixed this issue!
> 
> This is what I've done: I've identified the issue causing the redirect failure when there's an extra slash after the domain name. The problem is in the `getServerURL` function in the `packages/client/src/utils/config.ts` file. I've updated the function to properly handle URLs with or without trailing slashes.
> 
> Here's the change I made:
> 
> ```ts
> export const getServerURL = (serverURL: string): string => {
>   const result = removeEndingSplash(serverURL);
> 
>   return isLinkHttp(result) ? result : `https://${removeEndingSplash(result)}`;
> };
> ```
> 
> This change ensures that the server URL is properly formatted without trailing slashes, regardless of whether it's provided with http(s) or not.
> 
> I also created pull request: #2789
> 
> Caution
> 
> Disclaimer: This fix was created by Latta AI and you should never merge before you check the correctness of generated code!
> 
> This bug was fixed for free by Latta AI - https://latta.ai/ourmission

需要更新版本是吗
